spring:
  profiles: 
    active: 
    - dev
---
server:
  port: 8001
spring:
  profiles: dev
  application:
    name: microservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloudDB03
    username: root
    password: 123456
  dbcp2:
    min-idle: 5
    initial-size: 5
    max-total: 5
    max-wait-time: 200
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.atguigu.springcloud.entity
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
    
eureka:
  client:
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: dept-7001.com # 自定义服务名
    prefer-ip-address: true # 显示服务的ip地址
    
info:
  app.name: atguigu-microservicecloud-springcloudconfig02
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
  desc: 这是一个我测试的项目
---
server:
  port: 8001
spring:
  profiles: test
  application:
    name: microservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloudDB02
    username: root
    password: 123456
  dbcp2:
    min-idle: 5
    initial-size: 5
    max-total: 5
    max-wait-time: 200
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.atguigu.springcloud.entity
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
    
eureka:
  client:
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: dept-7001.com # 自定义服务名
    prefer-ip-address: true # 显示服务的ip地址
    
info:
  app.name: atguigu-microservicecloud-springcloudconfig02
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
  desc: 这是一个我测试的项目